"""add_chapter_templates_table

Revision ID: 38eed8de1ea3
Revises: 730c64a8e7fe
Create Date: 2026-01-06 23:15:56.958982

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '38eed8de1ea3'
down_revision = '730c64a8e7fe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chapter_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('preview_image_url', sa.String(length=500), nullable=True),
    sa.Column('template_data', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chapter_templates_created_by'), 'chapter_templates', ['created_by'], unique=False)
    op.create_index(op.f('ix_chapter_templates_id'), 'chapter_templates', ['id'], unique=False)
    op.create_index(op.f('ix_chapter_templates_is_public'), 'chapter_templates', ['is_public'], unique=False)
    op.create_index(op.f('ix_chapter_templates_name'), 'chapter_templates', ['name'], unique=False)
    op.alter_column('bookmarks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('uq_bookmarks_user_book', 'bookmarks', type_='unique')
    op.drop_constraint('uq_chapters_book_chapter_number', 'chapters', type_='unique')
    op.drop_constraint('uq_ratings_user_book', 'ratings', type_='unique')
    op.alter_column('reading_progress', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('uq_reading_progress_user_book', 'reading_progress', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_reading_progress_user_book', 'reading_progress', ['user_id', 'book_id'])
    op.alter_column('reading_progress', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_unique_constraint('uq_ratings_user_book', 'ratings', ['user_id', 'book_id'])
    op.create_unique_constraint('uq_chapters_book_chapter_number', 'chapters', ['book_id', 'chapter_number'])
    op.create_unique_constraint('uq_bookmarks_user_book', 'bookmarks', ['user_id', 'book_id'])
    op.alter_column('bookmarks', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_chapter_templates_name'), table_name='chapter_templates')
    op.drop_index(op.f('ix_chapter_templates_is_public'), table_name='chapter_templates')
    op.drop_index(op.f('ix_chapter_templates_id'), table_name='chapter_templates')
    op.drop_index(op.f('ix_chapter_templates_created_by'), table_name='chapter_templates')
    op.drop_table('chapter_templates')
    # ### end Alembic commands ###

